name: Move Files to Content Folder

on:
  push:
    paths:
      - 'website/**' # Trigger only if files in this folder are updated
  workflow_dispatch:  # Allow manual trigger via GitHub UI

jobs:
  move-files:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

     #compatible node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Specify a compatible Node.js version
          cache: 'npm'
      #node dependencies just in case
      - name: Install dependencies
        run: npm install

      # Create content directory if it doesn't exist
      - name: Ensure content folder exists
        run: mkdir -p website/content

      # Clean up content folder
      - name: Clean up content folder
        run: rm -rf website/content/*
      #reorganize Explorer with folders
      - name: reorganize Explorer
        run: |
          mkdir -p content/Articles content/"Book Notes" content/"Second Brain"
	        grep -l '#article' content/*.md | xargs -I{} mv "{}" content/Articles/
          grep -l '#book' content/*.md | xargs -I{} mv "{}" content/"Book Notes"/
	        find content -maxdepth 1 -type f -name '*.md' ! -name 'cv-portfolio.md' -exec mv {} content/"Second Brain"/ \;
	        mv content/cv-portfolio.md content/
      # move files from website subfolder to content subfolder
      - name: Move files to website/content
        run: |
          cp -r website/* content/

      # commit and push changes
      - name: Commit and push changes
        run: |
          git config user.name "aneurokumar"
          git config user.email "aneurokumar@gmail.com"
          git add . -A website/content/
          git commit -m "Move updated files to content folder" || true
          git push origin v4
        
      # deploy with quartz 
      - name: Deploy with Quartz
        run: |
          npx quartz sync 

