name: Move and Organize Content
on:
  push:
    paths:
      - 'website/**'
  workflow_dispatch:

jobs:
  process-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install

      - name: Setup git
        run: |
          git config user.name "aneurokumar"
          git config user.email "aneurokumar@gmail.com"
          git fetch --all
          git checkout v4
          git add content/
          git stash
          git pull origin v4
        
      - name: Setup content structure
        run: |
          mkdir -p content/{Articles,"Book Notes","Second Brain"}
          find content/Articles -type f ! -name "index.md" -delete || true
          find content/"Book Notes" -type f ! -name "index.md" -delete || true
          find content/"Second Brain" -type f ! -name "index.md" -delete || true
          find content -type f ! -name "index.md" -delete || true
      
      - name: unstage files
        run: git reset

      - name: Copy files from website to content
        run: cp -r sync/* content/

      - name: Create and run organization script
        run: |
          echo '#!/bin/bash
          
          process_file() {
              local file="$1"
              
              if [[ "$(basename "$file")" == "index.md" ]] || [[ ! "$file" =~ \.md$ ]]; then
                  return
              fi
              
              yaml_content=$(sed -n "/^---$/,/^---$/p" "$file")
              echo "Processing file: $file"
              
              if echo "$yaml_content" | grep -q "^[[:space:]]*- book$"; then
                  mv "$file" "content/Book Notes/$(basename "$file")"
                  echo "Moved $(basename "$file") to Book Notes"
              elif echo "$yaml_content" | grep -q "^[[:space:]]*- article$"; then
                  mv "$file" "content/Articles/$(basename "$file")"
                  echo "Moving $(basename "$file") to Articles"
              else
                  mv "$file" "content/Second Brain/$(basename "$file")"
                  echo "Moving $(basename "$file") to Second Brain"
              fi
          }

          find content -type f -name "*.md" | while read -r file; do
              process_file "$file"
          done

          echo "=== Organization Summary ==="
          echo "Articles: $(find content/Articles -type f ! -name "index.md" | wc -l) files"
          echo "Book Notes: $(find "content/Book Notes" -type f ! -name "index.md" | wc -l) files"
          echo "Second Brain: $(find "content/Second Brain" -type f ! -name "index.md" | wc -l) files"
          ' > organize-notes.sh

          chmod +x organize-notes.sh
          ./organize-notes.sh

      - name: Commit and push changes
        run: |
          git add -A content/
          git status
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Move and organize content files" || true
            git pull --rebase origin v4
            git push origin v4
          fi

      - name: Deploy with Quartz
        run: npx quartz sync
