name: Move and Organize Content
on:
  push:
    paths:
      - 'website/**'
  workflow_dispatch:

jobs:
  process-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Setup content structure
        run: |
        
          # Ensure base directories exist
      
          mkdir -p content/{Articles,"Book Notes","Second Brain"}
          
          # Clean existing content while preserving index.md
          find content/Articles -type f ! -name "index.md" -delete || true
          find content/"Book Notes" -type f ! -name "index.md" -delete || true
          find content/"Second Brain" -type f ! -name "index.md" -delete || true

      - name: Create and run organization script
        run: |
        
          echo '#!/bin/bash
          
          process_file() {
              local file="$1"
              
              # Skip non-markdown files and index files
              if [[ ! "$file" =~ \.md$ ]] || [[ "$(basename "$file")" == "index.md" ]]; then
                  return
              fi
              
              # Extract the YAML front matter
              yaml_content=$(sed -n "/^---$/,/^---$/p" "$file")
              
              # Debug: Show YAML content being processed
              echo "Processing file: $file"
              echo "YAML content:"
              echo "$yaml_content"
              
              if echo "$yaml_content" | grep -q "^[[:space:]]*- book$"; then
                  echo "Found book tag in $file"
                  cp "$file" "content/Book Notes/$(basename "$file")"
                  echo "Moved $(basename "$file") to Book Notes"
              elif echo "$yaml_content" | grep -q "^[[:space:]]*- article$"; then
                  echo "Found article tag in $file"
                  cp "$file" "content/Articles/$(basename "$file")"
                  echo "Moving $(basename "$file") to Articles"
              else
                  echo "No matching tags, moving to Second Brain"
                  cp "$file" "content/Second Brain/$(basename "$file")"
                  echo "Moving $(basename "$file") to Second Brain"
              fi
          }

          # Process all markdown files from the website directory
          find website -type f -name "*.md" | while read -r file; do
              process_file "$file"
          done

          # Print summary
          echo "=== Organization Summary ==="
          echo "Articles: $(find content/Articles -type f ! -name "index.md" | wc -l) files"
          echo "Book Notes: $(find content/Book Notes -type f ! -name "index.md" | wc -l) files"
          echo "Second Brain: $(find content/Second Brain -type f ! -name "index.md" | wc -l) files"
          ' > organize-notes.sh

          # Make the script executable and run it
          chmod +x organize-notes.sh
          ./organize-notes.sh

      - name: List contents for verification
        run: |
          echo "=== Content Directory Structure ==="
          find content -type f -name "*.md" | sort

      - name: Commit and push changes
        run: |
          git config user.name "aneurokumar"
          git config user.email "aneurokumar@gmail.com"
          git fetch origin v4
          git checkout v4
          git merge origin/v4 --no-edit
          git add -A content/
          git commit -m "Move and organize content files" || true
          git push origin v4

      - name: Deploy with Quartz
        run: npx quartz sync
